#!/usr/bin/env python3.5
## 102cipher.py for cipher in /home/florian/github/102cipher
## 
## Made by Florian Berthier
## Login   <florian.berthier@epitech.eu>
## 
## Started on  Tue Feb  8 18:42:56 2016 Florian Berthier
## Last update Thu Feb  9 15:43:25 2017 Florian Berthier
##
#!/usr/bin/python3.5
# -*-coding:Utf-8 -*

import sys
import math
import numpy as np

from pylab import *
from math import *

if len(sys.argv) != 3:
    sys.exit (84)

message = sys.argv[1]
key = sys.argv[2]

i = len(key)
size_matrix = round(sqrt(i))
if (size_matrix * size_matrix) > i:
    matrix_end = abs((size_matrix * size_matrix) - i)

i = 0
matrix_key = []
while i != len(key):
    matrix_key.append(ord(key[i]))
    i = i + 1
i = 0
while i != matrix_end:
    matrix_key.append(0)
    i = i + 1

i = 0
u = 0
print("Key matrix :")
while i != size_matrix:
    t = 0
    while t != size_matrix:
        print(matrix_key[u],end='\t')
        t = t + 1
        u = u + 1
    print('\n',end='\0')
    i = i + 1
    
i = 0
matrix_message = []
while i != len(message):
    matrix_message.append(ord(message[i]))
    i = i + 1
message_end = round(len(message) - 2) % size_matrix
i = 0
while i != message_end:
    matrix_message.append(0)
    i = i + 1 
        
i = 0
u = 0
size_message = (len(matrix_message) / size_matrix)
print("\nMatrix message :")
while i != size_message:
    t = 0
    while t != size_matrix:
        print(matrix_message[u],end='\t')
        t = t + 1
        u = u + 1
    print('\n',end='\0')
    i = i + 1
    
i = 0
q = 0
h = 0
k = 0
print("\nMessage encrypted :\n",end='\0')
message_encrypt = []
while i != len(matrix_message):
    if q == size_matrix:
        h = h + size_matrix
        q = 0
    k = q
    r = h
    n = 0
    save = 0
    while n != size_matrix:
        save = save + (matrix_key[k] * matrix_message[r])
        k = k + size_matrix
        r = r + 1
        n = n + 1
    message_encrypt.append(save)
    print(message_encrypt[i],end='\0')
    if i != len(matrix_message):
        print(' ',end='\0')
    i = i + 1
    q = q + 1

print('\n',end='\0')
